balancer/code-review

- rate-providers/registry.json
- rate-providers/stERNRateProvider.md
Related review request:
https://github.com/threerocks-defi/code-review/issues/44
> St ern rate provider

- rate-providers/registry.json
- rate-providers/rsETHRateProvider.md
This pr adds a review for the rsETHRateProvider on the Ethereum Mainnet. Related to https://github.com/balancer/code-review/issues/7
Outstanding:
> rsETHRateProviderMainnet

- rate-providers/registry.json
- rate-providers/rsEthRateProviderPolygonZKEVM.md
The pr adds the review for the rsETH Rate Provider on Polygon ZKEVM
outstanding activities:
> Rs eth rate provider poly zkevm

- rate-providers/registry.json
- rate-providers/sveth.md
> sveth review

- rate-providers/registry.json
- rate-providers/rswethRateProvider.md
> rswETH Rate Provider Review

- rate-providers/registry.json
- rate-providers/sDOLARateProvider.md
> SDOLA-rate-provider

- rate-providers/InstETHRateProvider.md
- rate-providers/registry.json
> review: add insteth review

- rate-providers/genETHRateProvider.md
- rate-providers/registry.json
This pr adds the review for genETH (LRT token).
> review: geneth

- rate-providers/registry.json
- rate-providers/wstethRateProvider.md
This pr is an addition to the registry of the time-tested wseth rateProviders on Mainnet & arbitrum. The conclusion marks them as safe without a review being added as part of this pr.
Fixes https://github.com/balancer/code-review/issues/20
> review: shortcut review for completeness

- rate-providers/PufEthRateProvider.md
- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
This pr adds two Rate Provider reviews:
- Gyroscope
- PufETH
> Pufeth rate provider

- rate-providers/MagpieMstETHRateProvider.md
- rate-providers/MagpieMswETHRateProvider.md
- rate-providers/registry.json
This pr adds reviews for both magpie rate Providers. It will cose:
- https://github.com/balancer/code-review/issues/29
- https://github.com/balancer/code-review/issues/28
> review: add magpie

- rate-providers/registry.json
- rate-providers/sUSDERateProvider.md
This PR adds the review for the usude Rate Provider.
> review: add susde

- rate-providers/registry.json
- rate-providers/sFRAXRateProvider.md
> sFRAX/FRAX ERC4626RateProvider

- rate-providers/registry.json
> Magie registry entry

- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
Fixes #44
This is not a new review. It is the same system being used on base. I verified the initial review contents for the base network.
> ERC4626RateProviderFactory on Base

- rate-providers/InceptionLRTRateProvider.md
- rate-providers/registry.json
Fixes #30
Similarly this pr is not a new pricing pipeline that gets added but a new "addition contract" that uses the same pricing logic.
> inankrETH Rate Provider

- rate-providers/registry.json
- rate-providers/rsETHRateProviderOptimism.md
> rsETH Rate Provider Optimism

- rate-providers/registry.json
- rate-providers/sweepRateProvider.md
- Update to (https://github.com/balancer/code-review/issues/32) with updated addresses.
> review: update addresses

- rate-providers/WrappedUsdPlusRateProvider.md
- rate-providers/registry.json
> network entry issue

- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
> StataUSDC Rate Provider Gnosis

- rate-providers/SyrupRateProvider.md
- rate-providers/registry.json
> Maple Rate Provider

- rate-providers/ezETHRateProviderMode.md
- rate-providers/registry.json
> ezETH Mode Rate Provider

- rate-providers/FraxtalPriceFeedProvider.md
- rate-providers/registry.json
> Fraxtal Feed Rate Providers

- rate-providers/registry.json
- rate-providers/rsETHRateProviderArbitrum.md
Fixes #81
This pr does not involve a new system. It uses the same functionality outlined in "rsETHRateProviderOptimism.md".
> rsETH Rate Provider - Arbitrum

- rate-providers/MellowRateProviders.md
- rate-providers/registry.json
Fixes #89
Outstanding activities
> Mellow Rate Providers

- rate-providers/registry.json
Updating the rate providers reviewed here to be considered safe as per their review. https://github.com/balancer/code-review/blob/main/rate-providers/TollgateChronicleRateProvider.md
> Gnosis TollgateChronicleRateProviders Safe

- rate-providers/registry.json
- rate-providers/wUSDMRateProvider.md
> wUSDM Rate Provider - Arbtrium

- rate-providers/registry.json
> fix optimism rseth

- rate-providers/registry.json
Tether GOLD being utilized in Xave FX pool format.
Relevant chainlink feed: https://etherscan.io/address/0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6#readContract
Rate provider: https://etherscan.io/address/0xEd29fBe335A0602Bf100825b533B12133FE523A3#readContract
Pool: https://etherscan.io/address/0x49f5bac6b54a983bee731abbf5441d7c726beb99#readContract
> Add XAUt Rate Provider

- rate-providers/registry.json
> dupe key in registry

- rate-providers/registry.json
- rate-providers/sUSXRateProvider.md
> sUSX Rate Providers

- rate-providers/registry.json
instETH (Optimism) - 0xd08C3F25862077056cb1b710937576Af899a4959
inETH (Optimism) - 0x5A7a183B6B44Dc4EC2E3d2eF43F98C5152b1d76d
inETH: https://optimistic.etherscan.io/address/0x210ABdFD989f3eE5C08614a8f4e096Cf8408f5DF 
instETH: https://optimistic.etherscan.io/address/0xC092E0a4f5a2AdF3CF91E27cf4B7d7917D12CA2B
inETH-ETH ER (OP): https://docs.chain.link/data-feeds/price-feeds/addresses?network=optimism&page=1&search=inETH
instETH-ETH ER (OP): https://docs.chain.link/data-feeds/price-feeds/addresses?network=optimism&page=1&search=instETH
> adding insteth and ineth in Optimism

- rate-providers/cdcEthRateProvider.md
- rate-providers/registry.json
> cdcETH Rate Provider

- rate-providers/registry.json
- rate-providers/sdeUSDRateProvider.md
> stdeUSD Rate Provider

- rate-providers/registry.json
- rate-providers/st-yETHRateProvider.md
> st-yETH Rate Provider

- rate-providers/AffineLiquidRestakingRateProvider.md
- rate-providers/registry.json
Fixes #96 
Fixes #97
This pr adds review for Affine's UltraLRT.
> Add Affine Ultra LRTs

- rate-providers/GYDConstantRateProvider.md
- rate-providers/registry.json
Fixes #137
Outstanding activities
> GYD Constant Rate Provider

- rate-providers/API3RateProvider.md
- rate-providers/registry.json
Fixes #138
Outstanding activities
> sDAI Rate Provider - Mode

- rate-providers/MellowRateProviders.md
- rate-providers/registry.json
Fixes #135
Outstanding activities
> Mellow dvstETH Rate Provider

- rate-providers/API3RateProvider.md
- rate-providers/registry.json
> Fraxtal wstETH API3 Rate Provider

- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
Adding review information and merging stataEthCrvUSD + stataEthLUSD to the registry. Corresponds to https://github.com/balancer/code-review/issues/155 and https://github.com/balancer/code-review/issues/154
> stataEthCrvUSD-&-stataEthLUSD

- rate-providers/API3RateProvider.md
- rate-providers/registry.json
Fixes #161
Outstanding issues:
> inETH Mode api3 Rate Provider

- rate-providers/ezEigenRateProvider.md
- rate-providers/registry.json
> ezEIGEN Rate Provider

- rate-providers/TreehouseRateProvider.md
- rate-providers/registry.json
> Treehouse tETH Rate Provider

- rate-providers/KernelRateProviders.md
- rate-providers/registry.json
Related: https://github.com/balancer/code-review/issues/100
After merge I will close https://github.com/balancer/code-review/pull/112
> review: Kernel rate providers

- rate-providers/registry.json
- rate-providers/wUSDMRateProviderPyth.md
> Pyth wUSDM Rate Provider - Mode

- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
> stataAvaUSDC ERC4626RateProvider on Avalanche

- rate-providers/HighGrowthEthRateProvider.md
- rate-providers/registry.json
> Kelp hgETH Rate Provider

- rate-providers/BlraSdaiRateProvider.md
- rate-providers/registry.json
> Gnosis BRLA Rate Provider

- rate-providers/MellowRateProviders.md
- rate-providers/registry.json
> rstETH Mellow Rate Provider

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
Silo v2 vaults, both erc4626 and rate providers
> Silo boosted

- rate-providers/MellowRateProviders.md
- rate-providers/registry.json
> Add DvstETH rp review

- erc4626/StatATokenV2Review.md
- erc4626/registry.json
- rate-providers/registry.json
- rate-providers/statATokenv2RateProvider.md
> Aave pyUSD Mainnet

- rate-providers/registry.json
An address has been placed under sonic network entry and moved to mainnet
> fix: move to mainnet

- erc4626/registry.json
Noticed we have "base" listed twice :upside_down_face:
> Fix erc4626 registry

- rate-providers/registry.json
I misunderstood the meaning of asset for rate provider within context of erc4626 vaults
> Fix assets for morpho vault rate providers on base

- erc4626/MorphoVaults/V1.1-Steakhouse.md
- erc4626/registry.json
- rate-providers/MorphoERC4626RateProviders.md
- rate-providers/registry.json
Closes #242 
- Added more vaults to the Steakhouse review file
- All vaults are [MetaMorphoV1_1](https://github.com/morpho-org/metamorpho-v1.1/blob/main/src/MetaMorphoV1_1.sol) contracts
- All vault tests are passing https://github.com/balancer/balancer-v3-erc4626-tests/pull/22
- Steakhouse USDQ and USDR vaults use a `TransparentUpgradeableProxy` contract for their asset where the admin is some old OG `MultiSigWallet` contract [written by Stefan George](https://medium.com/gnosis-pm/release-of-new-multisig-wallet-59b6811f7edc)
- Fetched admin by reading storage slot as instructed by the `TransparentUpgradeableProxy` contract
> Morpho Stakehouse USDR USDQ USDT

- erc4626/registry.json
- test/erc4626schema.test.js
> Add isCompatible flag to erc4626 registry

- .github/ISSUE_TEMPLATE/review-request.yml
Looks resolved in preview. https://github.com/Zen-Maxi/code-review/blob/main/.github/ISSUE_TEMPLATE/review-request.yml
> Issue template with erc4626 questions

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
Adding a new market to existing reviews
> adding silo ws market 25

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
erc4626 test https://github.com/balancer/balancer-v3-erc4626-tests/pull/29
> add new silo market

- erc4626/StatATokenV2Review.md
- erc4626/registry.json
- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
Adding aGHO to registry based on ERC4626 rate provider factory and fork test: https://github.com/balancer/balancer-v3-erc4626-tests/pull/30/files
> aGHO-Base-Rate-Provider-and-Vault

- rate-providers/registry.json
> Add sUSDz as ChainlinkRateProvider

- erc4626/FluidVaults.md
- erc4626/registry.json
- rate-providers/FluidRateProviders.md
- rate-providers/registry.json
> Fluid wETH Mainnet Arbitrum and Base

- rate-providers/OrbEthRateProvider.md
- rate-providers/registry.json
> orbETH Rate provider - Arbitrum

- rate-providers/CombinedRateProvider.md
- rate-providers/registry.json
- rate-providers/statATokenv2RateProvider.md
Adding rate provider for Aave-Eure vault and combined rate provider for Aave-Eure multiplied by the Euro chainlink oracle to permit a fully boosted Forex pool stablesurge pool at the request of karpatkey.
Dependent upon fork test success for Aave-Eure from @zekraken-bot
> Aave-EURe-Gnosis

- hooks/MevTaxHook.md
- hooks/registry.json
> review: add mev tax hook

- rate-providers/registry.json
Updates registry to properly consider TruMatic rate provider for Polygon. This is simply a typo from the original PR. Partners are requesting to join this pool.
> Moving-TruMatic-to-Polygon

- README.md
Fixes #290
Adds the factories to the readme
> ConstantRateProviderFactory on Base and Arbitrum

- rate-providers/registry.json
> fix-aEURC-Rate-Provider

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
Add new Silo markets and their rate providers
scETH: https://v2.silo.finance/markets/sonic/ptwstksceth29may-sceth-47
scUSD: https://v2.silo.finance/markets/sonic/ptausdc14aug-scusd-46
wETH: https://v2.silo.finance/markets/sonic/ptwstksceth29may-eth-35
USDC: https://app.silo.finance/markets/sonic/eggs-usdc-33
erc4626 tests: https://github.com/balancer/balancer-v3-erc4626-tests/pull/47
> Silo vaults

- rate-providers/RingsStakedRateprovider.md
- rate-providers/registry.json
Rate provider for the wrapped staked ring assets
> Ring wstk assets

- hooks/StableSurge.md
- hooks/StableSurgeHookV2.md
- hooks/registry.json
> Add stableSurgeHook V2

- rate-providers/BeefyEscrowedSonic.md
- rate-providers/registry.json
LST from Beefy: https://docs.beefy.finance/beefy-products/beefy-escrowed-tokens/bes
> beefy escrowed sonic

- rate-providers/registry.json
Request per Conduit Forex asset routing team.
> Add-EURC-Base-Chainlink-RateProvider

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
Silo USDC market 36: https://v2.silo.finance/markets/sonic/sts-usdc-36
erc4626 tests: https://github.com/balancer/balancer-v3-erc4626-tests/pull/48
> new silo market plus cleanup names

- hooks/AkronWeightedLVRFeeHook.md
- hooks/registry.json
> Akron swap hook review
