balancer/code-review

- rate-providers/ezETHRateProvider.md
- rate-providers/registry.json
Fixes #2
outstanding activities:
> ezETH Rate Provider Review

- rate-providers/registry.json
Chainlink rate provider for ETHx on Arbitrum.
Pool: https://app.balancer.fi/#/arbitrum/pool/0x7b54c44fbe6db6d97fd22b8756f89c0af16202cc00000000000000000000053c
Token: https://arbiscan.io/address/0xed65c5085a18fa160af0313e60dcc7905e944dc7#code
Rate contract: https://arbiscan.io/address/0x8581953084ffddbb82fc63f30f11bdb0e7300284
> ETHx-Arbitrum-Chainlink

- rate-providers/StakewiseRateProviderArbitrum.md
- rate-providers/registry.json
> StakeWise Staked ETH (osETH) Arbitrum Rate Provider

- rate-providers/InceptionLRTArbitrum.md
- rate-providers/registry.json
> Inception Arbitrum Rate Providers - inETH & instETH

- rate-providers/MellowRateProviders.md
- rate-providers/registry.json
This pr adds two new mellow lrt rps to the reviews & registry. They follow the same functionality & upgradeability pattern.
> review: add further mellow rps

- rate-providers/registry.json
- rate-providers/wUSDMRateProvider.md
> wUSDM Rate Provider - Optimism

- rate-providers/registry.json
- rate-providers/stBTCRateProvider.md
> Acre stBTC Rate Provider

- rate-providers/TokemakRateProvider.md
- rate-providers/registry.json
> balETH ERC4626 Rate Provider

- rate-providers/GYDConstantRateProvider.md
- rate-providers/registry.json
Adding GYD constant rate providers on mainnet: https://etherscan.io/address/0xD43F5a722e8e7355D790adda4642f392Dfb820a1 and Arbitrum:
https://arbiscan.io/address/0x72F6Da3b4bd0Ab7028F52339Ee3B1f94fffe2dD0
At the request of issue #150
> GYD-Constant-Rate-Providers-Sept-2024

- rate-providers/AffineLiquidRestakingRateProviders.md
- rate-providers/registry.json
> Affine Rate Providers (2)

- rate-providers/registry.json
- rate-providers/statATokenLMRateProvider.md
Adding the stataAvaWAVAX Rate provider. Admins are based on the Aave [PoolAddressesProvider](https://snowscan.xyz/address/0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb#readContract) per previous instances. Corresponding to https://github.com/balancer/code-review/issues/171
@mkflow27 is there any reason we do not reference the proxy admin as well? I find this to be a different address on [Avalanche](https://snowtrace.io/tx/0xb2d75568c992b57284fc8275becdab2b8e2cc32821017d17b70957f4b9d3a015/eventlog?chainid=43114#:~:text=%2C%20address)View%20Source-,Topics,-0) and [Gnosis](https://gnosisscan.io/address/0xe892E40C92c2E4D281Be59b2E6300F271d824E75#code), but maybe is not a risk or is outside our scope?
> stataAvaWAVAX-ERC4626-Rate-Provider

- rate-providers/USDCConstantRateProvider.md
- rate-providers/registry.json
Adds necessary rate providers to repo for Gyroscope proposal: https://forum.balancer.fi/t/bip-731-enable-several-e-clp-gauges-base/6148
This includes 3 constant rate providers which the format has been reviewed before for GYD, in this case for USDC. Also adding the chainlink rate provider deployed for wstETH on Base.
> USDCConstantRateProvider

- rate-providers/StatATokenTestnetRateProvider.md
- rate-providers/registry.json
Testnet rate providers for the static AAVE tokens balancer is using to test boosted pools feature of v3 contracts
@mendesfabio deployed these contracts :muscle: 
@MattPereira wants to include them so that API can offer the data for pool creation UI development purposes :pray:
> Testnet Rate Providers for Static AAVE tokens

- rate-providers/registry.json
For the rate provider registry, I accidentally put the underlying token addresses instead of the yield bearing, which I suspect is why API not returning the data I need
> Fix asset addresses for Aave testnet rate providers

- rate-providers/MarketRateTransformerRateProviders.md
- rate-providers/registry.json
- rate-providers/wUSDLPaxosRateProvider.md
Market Rate Transformers:
- Mainnet Lido Aave wstETH (Legacy wstETH Rate + Aave Statav2 Vault)
- Mainnet csUSDL - Steakhouse wUSDL vault (2 ERC4626 Vaults)
- Gnosis Aave wstETH (Chainlink + Aave Statav2 Vault)
Includes wUSDL raw rate provider on mainnet as well, this is identical to the Arbitrum implementation which was review several months ago.
> Adding Market Rate Transformers

- erc4626/StatATokenV2Review.md
- erc4626/registry.json
- erc4626/sDaiReview.md
- add gnosis and mainnet tokenized vaults as per code review
- checked vault and asset as per PROD boosted pools in [test UI](https://test.balancer.fi/pools?networks=MAINNET,GNOSIS&protocolVersion=3)
- please cross-check correct setup. Goal is for tokenized vault warnings to go away
IMPORTANT: main registry with ERC4626 rate providers still needs to be populated to register boosted pool rate providers as well!
Example: [Boosetd pool with waGNO and wstETH tokenized vaults](https://test.balancer.fi/pools/gnosis/v3/0x272d6be442e30d7c87390edeb9b96f1e84cecd8d)
> feat: add tokenized vaults to erc4626 registry

- rate-providers/registry.json
- rate-providers/sUSDXRateProviderReview.md
> sUSDX Rate Provider - Arbitrum

- rate-providers/GravitaRateProviders.md
- rate-providers/registry.json
> Gravita Rate Providers

- erc4626/MorphoVaults/V1-Incompatible-Gauntlet.md
- erc4626/MorphoVaults/V1-incompatible-Steakhouse.md
- erc4626/MorphoVaults/V1.1-Steakhouse.md
- erc4626/registry.json
- rate-providers/MarketRateTransformerRateProviders.md
- rate-providers/MorphoERC4626RateProviders.md
- rate-providers/registry.json
This PR does the following:
- Marks current MetaMorpho vaults as unsafe due to the potential flash loan incompatibility. The rate providers remain "safe" technically, but will not ever be used. Feel free to remove this contracts from the registry completely if that is cleaner.
- Adds the new v1.1 vaults for a first review to take place. Please note audits are not available for these vaults, I will ask Morpho for them on Monday January 6th. 
Details:
New Morpho deployments of v1.1 vaults have been made initially by Steakhouse and Coinshift. These pertain to a new wUSDL deployment, and a new Coinshift branded csUSDC vault. Please review the rate providers, run fork tests for the vaults, and provide feedback as needed. @mkflow27
This version comes with key improvements:
- Automated bad debt …
> MorphoV1.1-Coinshift-USDC-wUSDL-Additions

- erc4626/StatATokenV2Review.md
- erc4626/registry.json
- rate-providers/registry.json
- rate-providers/statATokenv2RateProvider.md
Adds ERC4626 and rate provider registration based on StataV2 wrappers for Ethena's USDe. Respective pool: https://balancer.fi/pools/ethereum/v3/0xc1D48bB722a22Cc6Abf19faCbE27470F08B3dB8c
> Supporting-Aave-ETH-USDe

- README.md
- rate-providers/registry.json
Adding in Chainlink rate provider for tETH / wstETH exchange rate. Also updating README due to wrong ChainlinkRateProviderFactory address in table.
tETH token address on Arbitrum to follow once deployed.
No need to merge this until address is provided.
> tETH-Arbitrum-CL-RP

- README.md
- rate-providers/registry.json
Adding AaveRateTransofrmerFactory addresses to new table on ReadMe page.
Also adding ezETH Chainlink rate provider from resepctive factory on Base due to the it being utilized in a rate transformer.
> AaveRateTransformerFactory-Table-ezETH-Base-CL-RP

- .github/ISSUE_TEMPLATE/review-request.yml
First step towards a new template to better filter rate providers meant for ERC4626 assets, and when buffers and fork tests are the required/intended.
Once we agree on a format and questions, we can work towards triggering a PR to the registry which considers this information to eliminate manual entry unless the information is proven not true by the review. I believe this is doable via a github action.
> Issue-template-with-ERC4626-questions

- rate-providers/registry.json
- rate-providers/sUSDSBaseRateProvider.md
> Create sUSDS Rate Provider on Base

- rate-providers/registry.json
Fixes #245
This rateProvider is a combination of 2 ChainLink price feed.
The factory should work by combining two rateProviders (which report an 18 decimal fixed point number) and scale it back to 18 decimals. 
This rp in my opinion does not require a separate review and it is just a combination of two ChainLink Rate providers.
> Treehouse ETH CombinedRateProvider

- rate-providers/cUSDOOpenEdenRateProvider.md
- rate-providers/registry.json
Close #267 
For context, it's standard erc4626 rate provider, so doesn't seem to have anything "unusual" worth highlighting.
The only bit of information that wasn't as trivial to find was the owner of the asset's proxy implementation.
I found it by tracking the `RoleGranted` event which is represented by the following topic0: `0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d`
You'll find that all roles are granted to the same EOA reported in the review.
> Add cUSDO open eden rate provider review

- rate-providers/registry.json
Adds the chainlink rate providers for wETH on Base and Arbitrum to permit LPs to join these volatile stablesurge pools.
> wETH-Chainlink-Oracle-Rate-Providers

- erc4626/FluidVaults.md
- erc4626/registry.json
- rate-providers/FluidRateProviders.md
- rate-providers/registry.json
Adding f-wstETH for Fluid. Lido intends to prioritize this over Lido Prime Aave market for wstETH.
Pending buffer seed from Fluid team.
> Fluid-wstETH-Mainnet

- erc4626/SiloV2Review.md
- erc4626/registry.json
- rate-providers/SiloWrappedRateprovider.md
- rate-providers/registry.json
Adding a new Silo market: scBTC, id 32: https://v2.silo.finance/markets/sonic/lbtc-scbtc-32
> scbtc-32 silo

- erc4626/StatATokenV2Review.md
- erc4626/registry.json
- rate-providers/MarketRateTransformerRateProviders.md
- rate-providers/registry.json
Adds rate transformer rate provider contract for EURC on aave market. To be paired aEURC-aGHO with yield exemption on Euro portion.
Chainlink EUR:USD combined with ERC4626 rate from Aave.
> aEURC-Base-RateTransformer

- erc4626/EulerVault.md
- erc4626/registry.json
- rate-providers/EulerWrappedRateprovider.md
- rate-providers/registry.json
The old cluster has socialized debt while the new one has it disabled.
Hence the old one needs to be removed as they are not safe. Adding the new wS market. https://sonicscan.org/address/0x90a804D316A06E00755444D56b9eF52e5C4F4D73#readProxyContract#F27 is set to 1 which is turning off the socialized debt
> change to new mev cluster

- rate-providers/registry.json
Conduit, Forex project working with Circle and Monerium assets primarily interested in deploying a stable surge pool using the Euro CL oracle feed on ETH mainnet.
This is the rate provider from the CL factory. Adding to registry to be whitelisted on the front end.
> EURC-RateProvider-CL-Mainnet
